// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Personal_Finance_Management.Repository;

#nullable disable

namespace Personal_Finance_Management.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsOnboardingCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_onboarding_completed");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("VND")
                        .HasColumnName("preferred_currency");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text")
                        .HasColumnName("status_reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_email");

                    b.HasIndex("LastLoginAt")
                        .HasDatabaseName("ix_accounts_last_login_at");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_username");

                    b.HasIndex("RoleId", "Status")
                        .HasDatabaseName("ix_accounts_role_status");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("chk_accounts_status", "\"status\" IN ('Active','Banned')");
                        });
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.AiSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKeyEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("api_key_encrypted");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<int>("MaxTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1000)
                        .HasColumnName("max_tokens");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<decimal>("Temperature")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0.7m)
                        .HasColumnName("temperature");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("UpdatedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_admin_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_settings");

                    b.HasIndex("UpdatedByAdminId")
                        .HasDatabaseName("ix_ai_settings_updated_by_admin_id");

                    b.ToTable("ai_settings", null, t =>
                        {
                            t.HasCheckConstraint("chk_ai_settings_max_tokens", "\"max_tokens\" > 0");

                            t.HasCheckConstraint("chk_ai_settings_temperature", "\"temperature\" >= 0 AND \"temperature\" <= 2");
                        });
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action_type");

                    b.Property<Guid>("ActorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("json")
                        .HasColumnName("metadata_json");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorAccountId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_actor_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Broadcast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CreatedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_admin_id");

                    b.Property<int>("DeliveredCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("delivered_count");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Queued")
                        .HasColumnName("status");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("All")
                        .HasColumnName("target_audience");

                    b.Property<int>("TargetCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("target_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_broadcasts");

                    b.HasIndex("CreatedByAdminId")
                        .HasDatabaseName("ix_broadcasts_created_by_admin_id");

                    b.HasIndex("Status", "ScheduledAt")
                        .HasDatabaseName("ix_broadcasts_status_scheduled_at");

                    b.ToTable("broadcasts", null, t =>
                        {
                            t.HasCheckConstraint("chk_broadcasts_counts", "\"target_count\" >= 0 AND \"delivered_count\" >= 0 AND \"delivered_count\" <= \"target_count\"");

                            t.HasCheckConstraint("chk_broadcasts_status", "\"status\" IN ('Queued','Sent','Failed','Cancelled')");
                        });
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("IsDefault", "IsActive")
                        .HasDatabaseName("ix_categories_default_active");

                    b.HasIndex("OwnerUserId", "IsActive")
                        .HasDatabaseName("ix_categories_owner_active");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.FinancialAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessTokenRef")
                        .HasColumnType("text")
                        .HasColumnName("access_token_ref");

                    b.Property<string>("AccountHolderName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("account_holder_name");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_type");

                    b.Property<string>("ConnectionMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("connection_mode");

                    b.Property<DateTimeOffset?>("ConsentExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consent_expires_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("VND")
                        .HasColumnName("currency");

                    b.Property<decimal>("CurrentBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("current_balance");

                    b.Property<string>("ExternalAccountId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("external_account_id");

                    b.Property<string>("ExternalAccountRef")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("external_account_ref");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("LastSyncCursor")
                        .HasColumnType("text")
                        .HasColumnName("last_sync_cursor");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("text")
                        .HasColumnName("last_sync_error");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("MaskedAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("masked_account_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ProviderCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_code");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_name");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("NeverSynced")
                        .HasColumnName("sync_status");

                    b.Property<DateTimeOffset?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WebhookSubscriptionId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("webhook_subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_financial_accounts");

                    b.HasIndex("SyncStatus")
                        .HasDatabaseName("ix_financial_accounts_sync_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_financial_accounts_user_id");

                    b.HasIndex("UserId", "IsDefault")
                        .HasDatabaseName("ix_financial_accounts_user_default");

                    b.ToTable("financial_accounts", null, t =>
                        {
                            t.HasCheckConstraint("chk_financial_accounts_account_type", "\"account_type\" IN ('Cash','Bank','EWallet','Other')");

                            t.HasCheckConstraint("chk_financial_accounts_connection_mode", "\"connection_mode\" IN ('Manual','LinkedApi')");

                            t.HasCheckConstraint("chk_financial_accounts_sync_status", "\"sync_status\" IN ('NeverSynced','Synced','Syncing','Error','Disconnected')");
                        });
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("LinkedJarId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_jar_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<decimal>("SavedAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("saved_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("target_amount");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_goals");

                    b.HasIndex("LinkedJarId")
                        .HasDatabaseName("ix_goals_linked_jar_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_goals_user_status");

                    b.ToTable("goals", null, t =>
                        {
                            t.HasCheckConstraint("chk_goals_amounts", "\"target_amount\" > 0 AND \"saved_amount\" >= 0");

                            t.HasCheckConstraint("chk_goals_status", "\"status\" IN ('Active','Completed','Cancelled')");
                        });
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BankCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bank_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int?>("EstimatedRows")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_rows");

                    b.Property<int>("FailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_count");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("FinancialAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("financial_account_id");

                    b.Property<string>("OriginalContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("original_content_type");

                    b.Property<int>("ParsedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("parsed_count");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stored_file_path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_import_jobs");

                    b.HasIndex("FinancialAccountId", "UploadedAt")
                        .HasDatabaseName("ix_import_jobs_account_uploaded_at");

                    b.HasIndex("UserId", "UploadedAt")
                        .HasDatabaseName("ix_import_jobs_user_uploaded_at");

                    b.ToTable("import_jobs", null, t =>
                        {
                            t.HasCheckConstraint("chk_import_jobs_counts", "\"parsed_count\" >= 0 AND \"failed_count\" >= 0 AND (\"estimated_rows\" IS NULL OR \"estimated_rows\" >= 0)");

                            t.HasCheckConstraint("chk_import_jobs_progress", "\"progress\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("chk_import_jobs_status", "\"status\" IN ('Pending','Processing','AwaitingReview','Completed','Failed')");
                        });
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.ImportTransactionDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("EditedCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("edited_category_id");

                    b.Property<Guid?>("EditedJarId")
                        .HasColumnType("uuid")
                        .HasColumnName("edited_jar_id");

                    b.Property<string>("EditedNote")
                        .HasColumnType("text")
                        .HasColumnName("edited_note");

                    b.Property<Guid?>("ImportJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_job_id");

                    b.Property<bool>("IsValid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_valid");

                    b.Property<string>("NormalizedPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("normalized_payload_json");

                    b.Property<string>("RawDescription")
                        .HasColumnType("text")
                        .HasColumnName("raw_description");

                    b.Property<int>("RowIndex")
                        .HasColumnType("integer")
                        .HasColumnName("row_index");

                    b.Property<DateTimeOffset?>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ValidationError")
                        .HasColumnType("text")
                        .HasColumnName("validation_error");

                    b.HasKey("Id")
                        .HasName("pk_import_transaction_drafts");

                    b.HasIndex("EditedCategoryId")
                        .HasDatabaseName("ix_import_transaction_drafts_edited_category_id");

                    b.HasIndex("EditedJarId")
                        .HasDatabaseName("ix_import_transaction_drafts_edited_jar_id");

                    b.HasIndex("ImportJobId")
                        .HasDatabaseName("ix_import_transaction_drafts_import_job_id");

                    b.HasIndex("ImportJobId", "RowIndex")
                        .IsUnique()
                        .HasDatabaseName("uq_import_transaction_drafts_job_row");

                    b.ToTable("import_transaction_drafts", null, t =>
                        {
                            t.HasCheckConstraint("chk_import_transaction_drafts_row_index", "(\"import_job_id\" IS NOT NULL AND \"row_index\" >= 0) OR (\"import_job_id\" IS NULL AND \"row_index\" < 0)");

                            t.HasCheckConstraint("chk_import_transaction_drafts_type", "\"type\" IS NULL OR \"type\" IN ('Income','Expense')");
                        });
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Jar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("balance");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("VND")
                        .HasColumnName("currency");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<Guid?>("JarSetupId")
                        .HasColumnType("uuid")
                        .HasColumnName("jar_setup_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_jars");

                    b.HasIndex("JarSetupId")
                        .HasDatabaseName("ix_jars_jar_setup_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_jars_user_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_jars_user_status");

                    b.ToTable("jars", null, t =>
                        {
                            t.HasCheckConstraint("chk_jars_status", "\"status\" IN ('Active','Paused','Archived')");
                        });
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.JarSetup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("MethodType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("method_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_jar_setups");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_jar_setups_user_id");

                    b.ToTable("jar_setups", null, t =>
                        {
                            t.HasCheckConstraint("chk_jar_setups_method_type", "\"method_type\" IN ('SixJars','Rule503020','Custom','Undecided')");
                        });
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid?>("BroadcastId")
                        .HasColumnType("uuid")
                        .HasColumnName("broadcast_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("json")
                        .HasColumnName("metadata_json");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("BroadcastId")
                        .HasDatabaseName("ix_notifications_broadcast_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_user_created_at");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notifications_user_unread")
                        .HasFilter("\"is_read\" = FALSE");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("chk_notifications_type", "\"type\" IN ('SpendingAlert','GoalUpdate','Reminder','System','Broadcast')");
                        });
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.OnboardingProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgeRange")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("age_range");

                    b.Property<string>("BudgetMethodPreference")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Undecided")
                        .HasColumnName("budget_method_preference");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FinancialGoalTypes")
                        .HasColumnType("text")
                        .HasColumnName("financial_goal_types");

                    b.Property<decimal?>("MonthlyIncome")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_income");

                    b.Property<string>("OccupationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("occupation_type");

                    b.Property<string>("RecommendedMethod")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("recommended_method");

                    b.Property<string>("SpendingChallenges")
                        .HasColumnType("text")
                        .HasColumnName("spending_challenges");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_onboarding_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_onboarding_profiles_user_id");

                    b.ToTable("onboarding_profiles", null, t =>
                        {
                            t.HasCheckConstraint("chk_onboarding_profiles_budget_method_preference", "\"budget_method_preference\" IN ('SixJars','Rule503020','Custom','Undecided')");

                            t.HasCheckConstraint("chk_onboarding_profiles_monthly_income", "\"monthly_income\" IS NULL OR \"monthly_income\" >= 0");

                            t.HasCheckConstraint("chk_onboarding_profiles_recommended_method", "\"recommended_method\" IS NULL OR \"recommended_method\" IN ('SixJars','Rule503020','Custom','Undecided')");
                        });
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<short?>("DayOfMonth")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_month");

                    b.Property<string>("Frequency")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frequency");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<short?>("NotifyDaysBefore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("notify_days_before");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("start_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reminders");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_reminders_category_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_reminders_user_status");

                    b.ToTable("reminders", null, t =>
                        {
                            t.HasCheckConstraint("chk_reminders_amount", "\"amount\" IS NULL OR \"amount\" >= 0");

                            t.HasCheckConstraint("chk_reminders_day_of_month", "\"day_of_month\" IS NULL OR \"day_of_month\" BETWEEN 1 AND 31");

                            t.HasCheckConstraint("chk_reminders_frequency", "\"frequency\" IS NULL OR \"frequency\" IN ('Daily','Weekly','Monthly','Quarterly','Yearly')");

                            t.HasCheckConstraint("chk_reminders_notify_days_before", "\"notify_days_before\" IS NULL OR \"notify_days_before\" >= 0");

                            t.HasCheckConstraint("chk_reminders_status", "\"status\" IN ('Active','Paused','Completed','Cancelled')");
                        });
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_code");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.SpendingLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AlertAtPercentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("alert_at_percentage");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("JarId")
                        .HasColumnType("uuid")
                        .HasColumnName("jar_id");

                    b.Property<decimal>("LimitAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("limit_amount");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("period");

                    b.Property<DateTimeOffset>("ResetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reset_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_spending_limits");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_spending_limits_category_id");

                    b.HasIndex("JarId")
                        .HasDatabaseName("ix_spending_limits_jar_id");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_spending_limits_user_active");

                    b.ToTable("spending_limits", null, t =>
                        {
                            t.HasCheckConstraint("chk_spending_limits_alert_percentage", "\"alert_at_percentage\" > 0 AND \"alert_at_percentage\" <= 100");

                            t.HasCheckConstraint("chk_spending_limits_amount", "\"limit_amount\" > 0");

                            t.HasCheckConstraint("chk_spending_limits_period", "\"period\" IN ('Daily','Monthly')");

                            t.HasCheckConstraint("chk_spending_limits_target", "\"jar_id\" IS NOT NULL OR \"category_id\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ExternalTransactionId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("external_transaction_id");

                    b.Property<Guid?>("FinancialAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("financial_account_id");

                    b.Property<Guid?>("FromJarId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_jar_id");

                    b.Property<Guid?>("ImportJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_job_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<decimal?>("JarBalanceAfterAllocation")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("jar_balance_after_allocation");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<string>("RawDescription")
                        .HasColumnType("text")
                        .HasColumnName("raw_description");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("json")
                        .HasColumnName("raw_payload_json");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("source_type");

                    b.Property<Guid?>("ToJarId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_jar_id");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<decimal>("TransactionsAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("transactions_amount");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_transactions_category_id");

                    b.HasIndex("FromJarId")
                        .HasDatabaseName("ix_transactions_from_jar_id");

                    b.HasIndex("ImportJobId")
                        .HasDatabaseName("ix_transactions_import_job_id");

                    b.HasIndex("ToJarId")
                        .HasDatabaseName("ix_transactions_to_jar_id");

                    b.HasIndex("FinancialAccountId", "TransactionDate")
                        .HasDatabaseName("ix_transactions_account_date")
                        .HasFilter("\"is_deleted\" = FALSE");

                    b.HasIndex("UserId", "TransactionDate")
                        .HasDatabaseName("ix_transactions_user_date")
                        .HasFilter("\"is_deleted\" = FALSE");

                    b.HasIndex("UserId", "CategoryId", "TransactionDate")
                        .HasDatabaseName("ix_transactions_user_category_date")
                        .HasFilter("\"is_deleted\" = FALSE");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("chk_transactions_amount_by_type", "(\"type\" = 'Income' AND \"transactions_amount\" > 0) OR (\"type\" = 'Expense' AND \"transactions_amount\" > 0) OR (\"type\" = 'Transfer' AND \"transactions_amount\" <> 0)");

                            t.HasCheckConstraint("chk_transactions_jar_direction", "\"from_jar_id\" IS NULL OR \"to_jar_id\" IS NULL OR \"from_jar_id\" <> \"to_jar_id\"");

                            t.HasCheckConstraint("chk_transactions_source_type", "\"source_type\" IN ('Manual','Imported','OCR','Jar','System')");

                            t.HasCheckConstraint("chk_transactions_type", "\"type\" IN ('Income','Expense', 'Transfer')");
                        });
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Account", b =>
                {
                    b.HasOne("Personal_Finance_Management.Repository.Entity.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.AiSetting", b =>
                {
                    b.HasOne("Personal_Finance_Management.Repository.Entity.Account", "UpdatedByAdmin")
                        .WithMany()
                        .HasForeignKey("UpdatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ai_settings_accounts_updated_by_admin_id");

                    b.Navigation("UpdatedByAdmin");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.AuditLog", b =>
                {
                    b.HasOne("Personal_Finance_Management.Repository.Entity.Account", "Account")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_accounts_actor_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Broadcast", b =>
                {
                    b.HasOne("Personal_Finance_Management.Repository.Entity.Account", "CreatedByAdmin")
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_broadcasts_accounts_created_by_admin_id");

                    b.Navigation("CreatedByAdmin");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Category", b =>
                {
                    b.HasOne("Personal_Finance_Management.Repository.Entity.Account", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_accounts_owner_user_id");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.FinancialAccount", b =>
                {
                    b.HasOne("Personal_Finance_Management.Repository.Entity.Account", "User")
                        .WithMany("FinancialAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_financial_accounts_accounts_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Goal", b =>
                {
                    b.HasOne("Personal_Finance_Management.Repository.Entity.Jar", "LinkedJar")
                        .WithMany()
                        .HasForeignKey("LinkedJarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_goals_jars_linked_jar_id");

                    b.HasOne("Personal_Finance_Management.Repository.Entity.Account", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goals_accounts_user_id");

                    b.Navigation("LinkedJar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.ImportJob", b =>
                {
                    b.HasOne("Personal_Finance_Management.Repository.Entity.FinancialAccount", "FinancialAccount")
                        .WithMany()
                        .HasForeignKey("FinancialAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_import_jobs_financial_accounts_financial_account_id");

                    b.HasOne("Personal_Finance_Management.Repository.Entity.Account", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_import_jobs_accounts_user_id");

                    b.Navigation("FinancialAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.ImportTransactionDraft", b =>
                {
                    b.HasOne("Personal_Finance_Management.Repository.Entity.Category", "EditedCategory")
                        .WithMany()
                        .HasForeignKey("EditedCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_import_transaction_drafts_categories_edited_category_id");

                    b.HasOne("Personal_Finance_Management.Repository.Entity.Jar", "EditedJar")
                        .WithMany()
                        .HasForeignKey("EditedJarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_import_transaction_drafts_jars_edited_jar_id");

                    b.HasOne("Personal_Finance_Management.Repository.Entity.ImportJob", "ImportJob")
                        .WithMany("Drafts")
                        .HasForeignKey("ImportJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_import_transaction_drafts_import_jobs_import_job_id");

                    b.Navigation("EditedCategory");

                    b.Navigation("EditedJar");

                    b.Navigation("ImportJob");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Jar", b =>
                {
                    b.HasOne("Personal_Finance_Management.Repository.Entity.JarSetup", "JarSetup")
                        .WithMany("Jars")
                        .HasForeignKey("JarSetupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_jars_jar_setups_jar_setup_id");

                    b.HasOne("Personal_Finance_Management.Repository.Entity.Account", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_jars_accounts_user_id");

                    b.Navigation("JarSetup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.JarSetup", b =>
                {
                    b.HasOne("Personal_Finance_Management.Repository.Entity.Account", "User")
                        .WithOne("JarSetup")
                        .HasForeignKey("Personal_Finance_Management.Repository.Entity.JarSetup", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_jar_setups_accounts_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Notification", b =>
                {
                    b.HasOne("Personal_Finance_Management.Repository.Entity.Broadcast", "Broadcast")
                        .WithMany("Notifications")
                        .HasForeignKey("BroadcastId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notifications_broadcasts_broadcast_id");

                    b.HasOne("Personal_Finance_Management.Repository.Entity.Account", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_accounts_user_id");

                    b.Navigation("Broadcast");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.OnboardingProfile", b =>
                {
                    b.HasOne("Personal_Finance_Management.Repository.Entity.Account", "User")
                        .WithOne("OnboardingProfile")
                        .HasForeignKey("Personal_Finance_Management.Repository.Entity.OnboardingProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_onboarding_profiles_accounts_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Reminder", b =>
                {
                    b.HasOne("Personal_Finance_Management.Repository.Entity.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reminders_categories_category_id");

                    b.HasOne("Personal_Finance_Management.Repository.Entity.Account", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reminders_accounts_user_id");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.SpendingLimit", b =>
                {
                    b.HasOne("Personal_Finance_Management.Repository.Entity.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_spending_limits_categories_category_id");

                    b.HasOne("Personal_Finance_Management.Repository.Entity.Jar", "Jar")
                        .WithMany()
                        .HasForeignKey("JarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_spending_limits_jars_jar_id");

                    b.HasOne("Personal_Finance_Management.Repository.Entity.Account", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_spending_limits_accounts_user_id");

                    b.Navigation("Category");

                    b.Navigation("Jar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Transaction", b =>
                {
                    b.HasOne("Personal_Finance_Management.Repository.Entity.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_categories_category_id");

                    b.HasOne("Personal_Finance_Management.Repository.Entity.FinancialAccount", "FinancialAccount")
                        .WithMany()
                        .HasForeignKey("FinancialAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_financial_accounts_financial_account_id");

                    b.HasOne("Personal_Finance_Management.Repository.Entity.Jar", "FromJar")
                        .WithMany()
                        .HasForeignKey("FromJarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_jars_from_jar_id");

                    b.HasOne("Personal_Finance_Management.Repository.Entity.ImportJob", "ImportJob")
                        .WithMany()
                        .HasForeignKey("ImportJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_import_jobs_import_job_id");

                    b.HasOne("Personal_Finance_Management.Repository.Entity.Jar", "ToJar")
                        .WithMany()
                        .HasForeignKey("ToJarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_jars_to_jar_id");

                    b.HasOne("Personal_Finance_Management.Repository.Entity.Account", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_accounts_user_id");

                    b.Navigation("Category");

                    b.Navigation("FinancialAccount");

                    b.Navigation("FromJar");

                    b.Navigation("ImportJob");

                    b.Navigation("ToJar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Account", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("FinancialAccounts");

                    b.Navigation("JarSetup");

                    b.Navigation("OnboardingProfile");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Broadcast", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.ImportJob", b =>
                {
                    b.Navigation("Drafts");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.JarSetup", b =>
                {
                    b.Navigation("Jars");
                });

            modelBuilder.Entity("Personal_Finance_Management.Repository.Entity.Role", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
