export const ROUTES = {
  ROOT: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  UNAUTHORIZED: "/unauthorized",
  DASHBOARD: "/dashboard",
  TRANSACTIONS: "/transactions",
  TRANSACTIONS_ADD: "/transactions/add",
  TRANSACTION_DETAIL: "/transactions/:id",
  IMPORTS_OCR: "/imports/ocr",
  ACCOUNTS: "/accounts",
  SETTINGS_BANK_ACCOUNTS: "/settings/bank-accounts",
  JARS: "/jars",
  BUDGET: "/budget",
  /** Cùng màn hình Ngân sách — khớp flow BE `/limits`. */
  LIMITS: "/limits",
  CATEGORIES: "/categories",
  REMINDERS: "/reminders",
  GOALS: "/goals",
  NOTIFICATIONS: "/notifications",
  PROFILE: "/profile",
  ONBOARDING: "/onboarding",
  VERIFY_EMAIL: "/verify-email",
  VERIFY_EMAIL_PENDING: "/verify-email/pending",
  ADMIN_DASHBOARD: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_NOTIFICATIONS: "/admin/notifications",
  ADMIN_AUDIT_LOGS: "/admin/audit-logs",
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_AI_SETTINGS: "/admin/ai-settings",
} as const;
